[package]
name = "shooter"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.14", features = ["file_watcher"]}
bevy_rapier3d = {version = "*", features = ["serde-serialize"]}
bevy_editor_pls = "0.9"
leafwing-input-manager = "0.15.0"
serde = "*"
ron = "*"
bitflags = "*"